const Keywords = [
  "university schedule companion",
  "student planner",
  "academic calendar",
  "class schedule",
  "homework planner",
  "assignment tracker",
  "study planner",
  "exam planner",
  "grade tracker",
  "GPA calculator",
  "course planner",
  "graduation planner",
  "programming languages",
  "computer architecture",
  "software engineering",
  "data science",
  "artificial intelligence",
  "machine learning",
  "cyber security",
  "computer networks",
  "database systems",
  "operating systems",
  "algorithms",
  "pharmacology",
  "toxicology",
  "pharmaceutics",
  "medicinal chemistry",
  "clinical pharmacy",
  "pharmacoepidemiology",
  "pharmacoeconomics",
  "pharmacy law",
  "pharmacy practice",
  "pharmacy research",
  "accounting",
  "economics",
  "finance",
  "marketing",
  "management",
  "entrepreneurship",
  "international business",
  "business law",
  "business ethics",
  "business statistics",
  "organic chemistry",
  "inorganic chemistry",
  "analytical chemistry",
  "physical chemistry",
  "biochemistry",
  "materials chemistry",
  "pharmaceutical chemistry",
  "polymer chemistry",
  "environmental chemistry",
  "food chemistry",
  "forensic chemistry",
  "ecology",
  "environmental biology",
  "environmental chemistry",
  "environmental geology",
  "environmental engineering",
  "environmental policy",
  "environmental law",
  "environmental economics",
  "environmental management",
  "environmental education",
  "environmental justice",
  "Harvard University graduate programs",
  "Stanford University computer science graduate program",
  "gaming",
  "web3",
  "blockchain",
  "cryptocurrency",
  "NFT",
  "metaverse",
  "play-to-earn",
  "decentralized finance",
  "gen Z",
  "millennial",
  "social media",
  "influencer",
  "content creator",
  "mental health",
  "sustainability",
  "diversity and inclusion",
  "entrepreneurship",
  "side hustle",
  "financial literacy",
  "personal development",
  "self-care",
  "travel",
  "food",
  "fashion",
  "beauty",
  "fitness",
  "entertainment",
  "sports",
  "music",
  "movies",
  "TV",
  "books",
  "podcasts",
  "technology",
  "gadgets",
  "innovation",
  "future of work",
  "remote work",
  "gig economy",
  "creator economy",
  "pubg",
  "call of duty",
  "fortnite",
  "apex legends",
  "league of legends",
  "dota 2",
  "counter strike",
  "overwatch",
  "valorant",
  "rainbow six siege",
  "rocket league",
  "fifa",
  "madden",
  "nba 2k",
  "nba live",
  "mlb the show",
  "nhl",
  "mortal kombat",
  "street fighter",
  "tekken",
  "soul calibur",
  "super smash bros",
  "super smash bros ultimate",
];

export const adKeywords = () => {
  return Keywords;
};
