name: Build Android

on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2


      - name: Check commit messages for build flag
        id: check-commit
        run: |
          if [[ $(git log -1 --pretty=%B) == *"--build"* ]]; then
            echo "Build flag detected in commit message. Proceeding with the workflow."
            echo "build_flag_detected=true" >> $GITHUB_ENV
          else
            echo "Build flag not detected in commit message. Skipping the workflow."
            echo "build_flag_detected=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Set up Expo Application Services (EAS)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: yarn install

      - name: Conditional Workflow
        if: env.build_flag_detected == 'true'
        run: |
          # Publish update
          eas build --platform android --profile production --non-interactive
